version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: chefiq
      POSTGRES_USER: chefiq
      POSTGRES_PASSWORD: chefiq123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    environment:
      CLICKHOUSE_DB: chefiq_analytics
      CLICKHOUSE_USER: chefiq
      CLICKHOUSE_PASSWORD: chefiq123
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222" # monitoring
    command: ["--jetstream", "--store_dir", "/data"]
    volumes:
      - nats_data:/data

volumes:
  postgres_data:
  clickhouse_data:
  nats_data:
